application:
  subdomain: rundeck
  upstreams:
    - location: /
      backend: http://rundeck:4440/
  public_path:
    - /
  injects:
    - id: login-autofill
      when:
        - /
      do:
        - src: builtin://simple-inject-password
          params:
            user: admin
            password: admin
services:
  rundeck:
    # rundeck/rundeck:5.18.0
    # upstream: rundeck/rundeck:7.0.1
    image: registry.lazycat.cloud/czyt/rundeck/rundeck:a19590df49c10d4f
    environment:
      - RUNDECK_GRAILS_URL=https://{{.S.AppDomain}}
      - RUNDECK_SERVER_FORWARDED=true
      - RUNDECK_SERVER_CONTEXTPATH=/
      - RUNDECK_SERVER_ADDRESS=0.0.0.0
      - TZ=Asia/Shanghai
      - RUNDECK_SECURITY_HTTPHEADERS_ENABLED=true
      - RUNDECK_SECURITY_HTTPHEADERS_PROVIDER_CSP_ENABLED=false
    binds:
      - /lzcapp/var/rundeck/data:/home/rundeck/server/data
      - /lzcapp/var/rundeck/plugins:/home/rundeck/libext
      - /lzcapp/var/rundeck/logs:/home/rundeck/server/logs
    setup_script: |
      chown -R rundeck:root /lzcapp/var/rundeck
    cpu_shares: 1024
    mem_limit: 2048M
    shm_size: 256m
    healthcheck:
      test:
        - CMD-SHELL
        - curl -f http://localhost:4440/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
